# Generated by Django 5.0.3 on 2024-03-26 06:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('exam_name', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_code', models.CharField(max_length=10, unique=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('options', models.JSONField(default={'1': '', '2': '', '3': '', '4': ''})),
                ('true_option', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.exams')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('exam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.exams')),
            ],
        ),
        migrations.CreateModel(
            name='Attemps_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_ans', models.IntegerField()),
                ('is_ans_true', models.BooleanField(default=False, null=True)),
                ('attempted', models.BooleanField(default=False)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.questions')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.students')),
            ],
            options={
                'unique_together': {('que_id', 'stu_id')},
            },
        ),
    ]
