# Generated by Django 5.0.3 on 2024-03-26 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='exam_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('options', models.JSONField(default={'1': '', '2': '', '3': '', '4': ''})),
                ('true_option', models.IntegerField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.IntegerField()),
                ('validity', models.BooleanField(default=False, null=True)),
                ('attempt', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.student')),
            ],
            options={
                'unique_together': {('question', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Attemps_log',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
